name: continous-integration
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - name: Download dependencies
        run: make go_get
      - name: Vet & Test codebase
        run: make go_test
      - name: Build
        run: make build